#!/bin/bash
# Reset the current macOS user's installation. Never run this script with sudo.
# Default is an inventory only; --apply opts into the printed removal plan.
set -euo pipefail

reset_usage() {
    cat <<'USAGE'
Usage: bash scripts/onboarding/reset.sh [--apply] [--cli /path/to/darkbloom]
                                      [--remove-model org/name ...]

Without --apply: show the plan, change nothing.
With --apply: stop the provider and watchdog, uninstall an optional fan helper,
ask the installed CLI to clear identity keys, remove local app/config/log/cache
data, and remove installer PATH lines. Shell files get a timestamped backup.

Models are kept by default. Repeat --remove-model for exact catalog IDs whose
shared Hugging Face cache you want deleted (including unfinished downloads).
Other apps using those same models will need to download them again.

Remove the Darkbloom enrollment profile in System Settings > General > Device
Management to test first-time enrollment again. Cloud account/history, browser
login, custom config/cache locations, and macOS system logs are not removed.
USAGE
}

reset_fail() { printf 'Reset stopped: %s\n' "$*" >&2; return 1; }

reset_model_path() {
    local model_id=$1
    # Exactly org/name; no traversal, control characters, or ambiguous cache IDs.
    [[ "$model_id" =~ ^[a-zA-Z0-9_][a-zA-Z0-9_.-]*/[a-zA-Z0-9_][a-zA-Z0-9_.-]*$ ]] || {
        reset_fail "Use an exact model ID such as org/model: $model_id"; return 1;
    }
    printf '%s/.cache/huggingface/hub/models--%s\n' "$reset_home" "${model_id//\//--}"
}

reset_check_path() {
    local target=$1 parent
    case "$target" in "$reset_home"/*) ;; *) reset_fail "Path is outside your home: $target"; return 1 ;; esac
    # Never follow a symlink in an ancestor. A leaf symlink is only unlinked.
    parent=${target%/*}
    while [ "$parent" != / ]; do
        [ ! -L "$parent" ] || { reset_fail "Symlinked parent requires manual review: $parent"; return 1; }
        parent=${parent%/*}
        [ -n "$parent" ] || parent=/
    done
}

reset_remove_path() {
    reset_check_path "$1" || return 1
    [ -e "$1" ] || [ -L "$1" ] || return 0
    /bin/rm -rf -- "$1"
}

reset_filter_shell() {
    # Only exact lines generated by known installers. Keep user customizations.
    /usr/bin/awk '
      $0 == "# Darkbloom" || $0 == "# EigenInference" { next }
      $0 == "export PATH=\"$HOME/.darkbloom/bin:$PATH\"" { next }
      $0 == "export PATH=\"$HOME/.eigeninference/bin:$PATH\"" { next }
      $0 == "export PATH=\"$HOME/.dginf/bin:$PATH\"" { next }
      { print }
    ' "$1"
}

reset_shell_file() {
    local rc=$1 temporary backup
    [ -f "$rc" ] || return 0
    reset_check_path "$rc" || return 1
    [ ! -L "$rc" ] || { reset_fail "Shell file is a symlink; edit it manually: $rc"; return 1; }
    temporary=$(/usr/bin/mktemp "${rc}.darkbloom-reset.XXXXXX")
    reset_filter_shell "$rc" > "$temporary"
    if /usr/bin/cmp -s "$rc" "$temporary"; then
        /bin/rm -f "$temporary"
        return 0
    fi
    backup="${rc}.before-darkbloom-reset.$(/bin/date +%Y%m%d-%H%M%S).$$"
    /bin/cp -p "$rc" "$backup"
    # Write through the existing inode to preserve permissions/ACLs.
    /bin/cat "$temporary" > "$rc"
    /bin/rm -f "$temporary"
    printf 'Shell backup: %s\n' "$backup"
}

reset_main() {
    local apply=0 cli='' target model_id label rc link_target pid_name
    local reset_home=${HOME:?HOME must be set}
    local paths=() models=() shell_files=()
    while [ "$#" -gt 0 ]; do
        case "$1" in
            --apply) apply=1; shift ;;
            --cli) [ "$#" -ge 2 ] || { reset_usage; return 2; }; cli=$2; shift 2 ;;
            --remove-model) [ "$#" -ge 2 ] || { reset_usage; return 2; }; models+=("$2"); shift 2 ;;
            -h|--help) reset_usage; return 0 ;;
            *) reset_fail "Unknown argument: $1"; return 2 ;;
        esac
    done
    [ "$(/usr/bin/uname -s)" = Darwin ] || { reset_fail 'This reset is for macOS.'; return 1; }
    [ "$(/usr/bin/id -u)" != 0 ] || { reset_fail 'Run as your normal user, without sudo.'; return 1; }
    case "$reset_home" in /*) ;; *) reset_fail 'HOME must be absolute.'; return 1 ;; esac
    [ "$reset_home" != / ] || { reset_fail 'HOME cannot be /.'; return 1; }

    for target in .darkbloom .eigeninference .dginf .config/darkbloom .config/eigeninference \
        'Library/Application Support/darkbloom' 'Library/Application Support/eigeninference' \
        'Library/Caches/darkbloom' \
        Library/LaunchAgents/io.darkbloom.provider.plist \
        Library/LaunchAgents/dev.darkbloom.provider.plist \
        Library/LaunchAgents/io.darkbloom.watchdog.plist; do
        paths+=("$reset_home/$target")
    done
    for model_id in "${models[@]+${models[@]}}"; do
        paths+=("$(reset_model_path "$model_id")")
    done
    for rc in .zshrc .bashrc .bash_profile .profile; do shell_files+=("$reset_home/$rc"); done
    if [ -z "$cli" ]; then
        for target in "$reset_home/.darkbloom/bin/darkbloom" "$reset_home/.darkbloom/Darkbloom.app/Contents/MacOS/darkbloom"; do
            if [ -x "$target" ]; then cli=$target; break; fi
        done
    fi

    printf 'Darkbloom reset for %s\n\n' "$reset_home"
    printf 'CLI for service and key cleanup: %s\n' "${cli:-not found; supply --cli to apply}"
    printf '\nRemove these existing paths:\n'
    for target in "${paths[@]}"; do
        if [ -e "$target" ] || [ -L "$target" ]; then printf '  %s\n' "$target"; fi
    done
    printf '\nClean exact installer PATH lines in existing shell files:\n'
    for rc in "${shell_files[@]}"; do [ ! -f "$rc" ] || printf '  %s\n' "$rc"; done
    printf '\nStop provider/watchdog; uninstall fan helper if present (sudo for that step only).\n'
    printf 'Remove /usr/local/bin/darkbloom only if it points into this user’s install.\n'
    printf 'Clear local identity through darkbloom unenroll; manually remove the MDM profile.\n'
    printf 'Shared models are kept except for explicitly named --remove-model IDs.\n'
    [ "$apply" = 1 ] || { printf '\nInventory only. Run again with --apply to execute.\n'; return 0; }

    [ -n "$cli" ] && [ -x "$cli" ] || { reset_fail 'A working installed CLI is required for key cleanup; use --cli /path/to/darkbloom.'; return 1; }
    # Check every target before stopping services or deleting anything.
    for target in "${paths[@]}" "${shell_files[@]}"; do reset_check_path "$target" || return 1; done
    for target in "$reset_home/.darkbloom" "$reset_home/.config/darkbloom" \
        "$reset_home/.config/eigeninference" "$reset_home/Library/Application Support/eigeninference" \
        "${shell_files[@]}"; do
        [ ! -L "$target" ] || { reset_fail "CLI cleanup or shell editing would follow a symlink: $target"; return 1; }
    done

    /usr/bin/env DARKBLOOM_NO_UPDATE_CHECK=1 "$cli" stop --uninstall
    for label in io.darkbloom.watchdog io.darkbloom.provider dev.darkbloom.provider; do
        if /bin/launchctl print "gui/$(/usr/bin/id -u)/$label" >/dev/null 2>&1; then
            reset_fail "Service still loaded: $label. Resolve it before deleting files."; return 1
        fi
    done
    for pid_name in darkbloom eigeninference dginf; do
        if /usr/bin/pgrep -u "$(/usr/bin/id -u)" -x "$pid_name" >/dev/null; then
            reset_fail "A $pid_name process is still running. Close foreground sessions and retry."; return 1
        fi
    done
    if [ -e /Library/PrivilegedHelperTools/io.darkbloom.fan-helper ] \
        || [ -e /Library/LaunchDaemons/io.darkbloom.fan.plist ] \
        || [ -e '/Library/Application Support/Darkbloom/fan-session.json' ] \
        || [ -e '/Library/Application Support/Darkbloom/fan-policy.json' ]; then
        # Must restore macOS fan control before deleting privileged helper files.
        /usr/bin/sudo "$cli" fan uninstall
    fi
    /usr/bin/env -u DARKBLOOM_AUTH_TOKEN_PATH DARKBLOOM_NO_UPDATE_CHECK=1 "$cli" unenroll --force
    for rc in "${shell_files[@]}"; do reset_shell_file "$rc" || return 1; done
    if [ -L /usr/local/bin/darkbloom ]; then
        link_target=$(/usr/bin/readlink /usr/local/bin/darkbloom)
        case "$link_target" in
            "$reset_home/.darkbloom/"*|"$reset_home/.eigeninference/"*|"$reset_home/.dginf/"*)
                if [ -w /usr/local/bin ]; then /bin/rm /usr/local/bin/darkbloom
                else /usr/bin/sudo /bin/rm /usr/local/bin/darkbloom; fi ;;
        esac
    fi
    for target in "${paths[@]}"; do reset_remove_path "$target" || return 1; done
    printf '\nLocal reset finished. Remove the Darkbloom profile in System Settings to repeat enrollment.\n'
    printf 'Open a new terminal before reinstalling.\n'
}

if [ "${BASH_SOURCE[0]}" = "$0" ]; then reset_main "$@"; fi
